### ISSUE TITLE
Are the scores just based on one page of the websites?

### ISSUE THREAD

**Issue by mtboesch** [civichackingagency/gov-metadata#40]
I am curious as to what the domain scoring is based on? Is it just one page our an average of pages across the site?

**Comment by Narlotl** [comment]
The scores are based on where the basic URL redirects to.
For example, AMTRAK's (amtrakoig.gov) score is based on the page at [https://amtrakoig.gov/](https://amtrakoig.gov/).
```javascript
{
    "status":200,
    "url":"amtrakoig.gov",
    "name":"Amtrak",
    "redirect":"https://amtrakoig.gov/"
}
```

**Comment by mtboesch** [comment]
So only one page and that is representative of a whole site? So for example nsf.gov is scored for what is just on www.nsf.gov<http://www.nsf.gov>? Has new.nsf.gov been checked?

From: Elias Fretwell ***@***.***>
Sent: Thursday, February 1, 2024 10:34 AM
To: civichackingagency/gov-metadata ***@***.***>
Cc: Boesch, Matt ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [civichackingagency/gov-metadata] Are the scores just based on one page of the websites? (Issue #40)

This email originated from outside of the National Science Foundation. Do not click links or open attachments unless you recognize the sender and know the content is safe.


The scores are based on where the basic URL redirects to.
For example, AMTRAK's (amtrakoig.gov) score is based on the page at https://amtrakoig.gov/.

{

    "status":200,

    "url":"amtrakoig.gov",

    "name":"Amtrak",

    "redirect":"https://amtrakoig.gov/"

}

**Comment by Narlotl** [comment]
Yes, due to a limit on power, the one page is what we use to represent the whole site. In your case though, [www.nsf.gov](https://www.nsf.gov) and [new.nsf.gov](https://new.nsf.gov) are the same.

**Comment by mtboesch** [comment]
Thanks Elias. Would it  be possible to get a scan on another www.nsf.gov<http://www.nsf.gov> page like https://www.nsf.gov/staff/ or https://www.nsf.gov/dir/index.jsp?org=BIO? These are what we consider legacy pages. We are moving to a modernized platform, which is currently running on new.nsf.gov. As you correctly pointed out, the www.nsf.gov<http://www.nsf.gov> home page is the same as the new.nsf.gov home page, because for that page only on www.nsf.gov<http://www.nsf.gov>, it is being served from the new platform. The purpose of scanning the legacy pages would show us the incremental improvement of the new platform over the legacy platform pages. FYI - We plan to add the missing metadata tags in future releases of the modernized platform application.

From: Elias Fretwell ***@***.***>
Sent: Thursday, February 1, 2024 11:29 AM
To: civichackingagency/gov-metadata ***@***.***>
Cc: Boesch, Matt ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [civichackingagency/gov-metadata] Are the scores just based on one page of the websites? (Issue #40)

This email originated from outside of the National Science Foundation. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Yes, due to a limit on power, the one page is what we use to represent the whole site. In your case though, www.nsf.gov<https://www.nsf.gov> and new.nsf.gov<https://new.nsf.gov> are the same.

**Comment by Narlotl** [comment]
Sure, I can add a scan for both the legacy and new NSF pages. We're also adding history, so you can see the changes.

**Comment by Narlotl** [comment]
I've added the two sites and the history is being tracked.
[New](https://gov-metadata.civichackingagency.org/profile.html?domain=new.nsf.gov)
[Old](https://gov-metadata.civichackingagency.org/profile.html?domain=nsf.gov/staff)
