### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/gov-metadata#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lukefretwell** [comment]
@Narlotl did you do this, because it looks like it's working?

https://gov-metadata.civichackingagency.org/docs/metadata

**Comment by Narlotl** [comment]
I tried to and messed up the Jekyll, so it might have installed when I reset Jekyll.
