### ISSUE TITLE
Update data: Medicare.gov

### ISSUE THREAD

**Issue by arisaves** [civichackingagency/gov-metadata#60]
Domain: Medicare.gov

We are due to release some changes on 2/27 and I'd like to request an update for 2/27 after 4:00 ET -- thanks!

**Comment by lukefretwell** [comment]
Done: https://gov-metadata.civichackingagency.org/profile/?domain=medicare.gov

**Comment by arisaves** [comment]
Awesome, thank you so much :D Loving this tool so far. As a best practice, is it good to make a request here whenever we expect to have an update?

**Comment by lukefretwell** [comment]
@arisaves thank you for the feedback. More to come.

Yes, we're updating the data, but not on an automated schedule, so it's a little random at the moment. Making the issue request will speed up the update process.
