### ISSUE TITLE
Cards not spaced uniformly

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/gov-metadata#75]
**Describe the bug**

Looks like cards for each of the pages aren't spaced the same. We should probably do this in the CSS.

* Spacing: https://gov-metadata.civichackingagency.org/profile/?domain=digital.gov#
* No spacing: https://gov-metadata.civichackingagency.org/profile/?domain=digital.gov#url

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Narlotl** [comment]
Which spacing should we use, the one with or without the gap?

**Comment by lukefretwell** [comment]
With, I think mx-3 or something like that.
