### ISSUE TITLE
Dashboard clean-up

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/gov-metadata#78]
**Describe the bug**

* Use dashboard icon
* Remove border below metadata and URL cards
* Add hover class that's just slightly lighter than background

Reference: https://gov-metadata.civichackingagency.org/profile/?domain=digital.gov#

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Narlotl** [comment]
What dashboard icon? https://fontawesome.com/search?q=dashboard&o=r&m=free

**Comment by lukefretwell** [comment]
Sorry gauge: https://fontawesome.com/icons/gauge?f=classic&s=solid
