### ISSUE TITLE
Update data:https://openpaymentsdata.cms.gov

### ISSUE THREAD

**Issue by akaroleff** [civichackingagency/gov-metadata#93]
Please scan domain: https://openpaymentsdata.cms.gov/

**Comment by Narlotl** [comment]
Done: https://gov-metadata.civichackingagency.org/profile/?domain=openpaymentsdata.cms.gov#/

I also just made a guide for running the tool with your own set of domains. If you want to do your own with CMS/Medicaid domains, check out [RUNNING.md](RUNNING.md).
